sudo: false
language: python
python: 3.5
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py35
  - TOX_ENV=py36
  - TOX_ENV=lint
matrix:
  include:
    - env: TOX_ENV=py36
      python: "3.6"
install: pip install tox
script: tox -e $TOX_ENV
cache: pip
